package entity;
// Generated Nov 30, 2017 10:42:49 PM by Hibernate Tools 4.3.1



/**
 * DiagramId generated by hbm2java
 */
public class DiagramId  implements java.io.Serializable {


     private int iddiagram;
     private int idstudent;

    public DiagramId() {
    }

    public DiagramId(int iddiagram, int idstudent) {
       this.iddiagram = iddiagram;
       this.idstudent = idstudent;
    }
   
    public int getIddiagram() {
        return this.iddiagram;
    }
    
    public void setIddiagram(int iddiagram) {
        this.iddiagram = iddiagram;
    }
    public int getIdstudent() {
        return this.idstudent;
    }
    
    public void setIdstudent(int idstudent) {
        this.idstudent = idstudent;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DiagramId) ) return false;
		 DiagramId castOther = ( DiagramId ) other; 
         
		 return (this.getIddiagram()==castOther.getIddiagram())
 && (this.getIdstudent()==castOther.getIdstudent());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIddiagram();
         result = 37 * result + this.getIdstudent();
         return result;
   }   


}


