package entity;
// Generated Nov 30, 2017 10:42:49 PM by Hibernate Tools 4.3.1



/**
 * Diagram generated by hbm2java
 */
public class Diagram  implements java.io.Serializable {


     private DiagramId id;
     private Exercise exercise;
     private Student student;
     private String serial;
     private Evaluation evaluation;

    public Diagram() {
    }

	
    public Diagram(DiagramId id, Exercise exercise, Student student, String serial) {
        this.id = id;
        this.exercise = exercise;
        this.student = student;
        this.serial = serial;
    }
    public Diagram(DiagramId id, Exercise exercise, Student student, String serial, Evaluation evaluation) {
       this.id = id;
       this.exercise = exercise;
       this.student = student;
       this.serial = serial;
       this.evaluation = evaluation;
    }
   
    public DiagramId getId() {
        return this.id;
    }
    
    public void setId(DiagramId id) {
        this.id = id;
    }
    public Exercise getExercise() {
        return this.exercise;
    }
    
    public void setExercise(Exercise exercise) {
        this.exercise = exercise;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public Evaluation getEvaluation() {
        return this.evaluation;
    }
    
    public void setEvaluation(Evaluation evaluation) {
        this.evaluation = evaluation;
    }




}


