package entity;
// Generated Dec 4, 2017 4:46:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercise generated by hbm2java
 */
public class Exercise  implements java.io.Serializable {


     private Integer idexercise;
     private String equation;
     private int eqtype;
     private String solution;
     private Set schoolgroups = new HashSet(0);
     private Set diagrams = new HashSet(0);

    public Exercise() {
    }

	
    public Exercise(String equation, int eqtype, String solution) {
        this.equation = equation;
        this.eqtype = eqtype;
        this.solution = solution;
    }
    public Exercise(String equation, int eqtype, String solution, Set schoolgroups, Set diagrams) {
       this.equation = equation;
       this.eqtype = eqtype;
       this.solution = solution;
       this.schoolgroups = schoolgroups;
       this.diagrams = diagrams;
    }
   
    public Integer getIdexercise() {
        return this.idexercise;
    }
    
    public void setIdexercise(Integer idexercise) {
        this.idexercise = idexercise;
    }
    public String getEquation() {
        return this.equation;
    }
    
    public void setEquation(String equation) {
        this.equation = equation;
    }
    public int getEqtype() {
        return this.eqtype;
    }
    
    public void setEqtype(int eqtype) {
        this.eqtype = eqtype;
    }

    public String getSolution() {
        return solution;
    }

    public void setSolution(String solution) {
        this.solution = solution;
    }
    
    public Set getSchoolgroups() {
        return this.schoolgroups;
    }
    
    public void setSchoolgroups(Set schoolgroups) {
        this.schoolgroups = schoolgroups;
    }
    public Set getDiagrams() {
        return this.diagrams;
    }
    
    public void setDiagrams(Set diagrams) {
        this.diagrams = diagrams;
    }
}


