package entity;
// Generated Nov 30, 2017 10:42:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Schoolgroup generated by hbm2java
 */
public class Schoolgroup  implements java.io.Serializable {


     private Integer idgroup;
     private Teacher teacher;
     private String name;
     private Set students = new HashSet(0);
     private Set exercises = new HashSet(0);

    public Schoolgroup() {
    }

	
    public Schoolgroup(Teacher teacher, String name) {
        this.teacher = teacher;
        this.name = name;
    }
    public Schoolgroup(Teacher teacher, String name, Set students, Set exercises) {
       this.teacher = teacher;
       this.name = name;
       this.students = students;
       this.exercises = exercises;
    }
   
    public Integer getIdgroup() {
        return this.idgroup;
    }
    
    public void setIdgroup(Integer idgroup) {
        this.idgroup = idgroup;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
    public Set getExercises() {
        return this.exercises;
    }
    
    public void setExercises(Set exercises) {
        this.exercises = exercises;
    }




}


