package entity;
// Generated Dec 2, 2017 5:03:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int iduser;
     private Schoolgroup schoolgroup;
     private User user;
     private Set diagrams = new HashSet(0);

    public Student() {
    }

	
    public Student(Schoolgroup schoolgroup, User user) {
        this.schoolgroup = schoolgroup;
        this.user = user;
    }
    public Student(Schoolgroup schoolgroup, User user, Set diagrams) {
       this.schoolgroup = schoolgroup;
       this.user = user;
       this.diagrams = diagrams;
    }
   
    public int getIduser() {
        return this.iduser;
    }
    
    public void setIduser(int iduser) {
        this.iduser = iduser;
    }
    public Schoolgroup getSchoolgroup() {
        return this.schoolgroup;
    }
    
    public void setSchoolgroup(Schoolgroup schoolgroup) {
        this.schoolgroup = schoolgroup;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getDiagrams() {
        return this.diagrams;
    }
    
    public void setDiagrams(Set diagrams) {
        this.diagrams = diagrams;
    }




}


