package entity;
// Generated Dec 11, 2017 3:40:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private int iduser;
     private User user;
     private Set schoolgroups = new HashSet(0);

    public Teacher() {
    }

	
    public Teacher(User user) {
        this.user = user;
    }
    public Teacher(User user, Set schoolgroups) {
       this.user = user;
       this.schoolgroups = schoolgroups;
    }
   
    public int getIduser() {
        return this.iduser;
    }
    
    public void setIduser(int iduser) {
        this.iduser = iduser;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getSchoolgroups() {
        return this.schoolgroups;
    }
    
    public void setSchoolgroups(Set schoolgroups) {
        this.schoolgroups = schoolgroups;
    }




}


