package entity;
// Generated Dec 2, 2017 5:03:56 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String firstnames;
     private String surnames;
     private String username;
     private String password;
     private Administrator administrator;
     private Teacher teacher;
     private Student student;

    public User() {
    }

	
    public User(String firstnames, String surnames, String username, String password) {
        this.firstnames = firstnames;
        this.surnames = surnames;
        this.username = username;
        this.password = password;
    }
    public User(String firstnames, String surnames, String username, String password, Administrator administrator, Teacher teacher, Student student) {
       this.firstnames = firstnames;
       this.surnames = surnames;
       this.username = username;
       this.password = password;
       this.administrator = administrator;
       this.teacher = teacher;
       this.student = student;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getFirstnames() {
        return this.firstnames;
    }
    
    public void setFirstnames(String firstnames) {
        this.firstnames = firstnames;
    }
    public String getSurnames() {
        return this.surnames;
    }
    
    public void setSurnames(String surnames) {
        this.surnames = surnames;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


